= Lab 3 - TDD Aggregate Repository - Create Kitchen Repositories and Add Domain Events

When persisting Aggregate instances using Event Sourcing, we persist an "Add Event" rather than the instance itself. This event will contain the initial state snapshot on which we will apply all subsequent events to "rehydrate" the current state of the object.

In this lab, we'll begin filling in the details necessary for a Repository to "add" an Aggregate instance.

We will complete two stories:

. A Repository must be able to provide the next available identity, or `Ref` for an Aggregate.
. A Repository must properly construct and publish a `RepositoryAddEvent`.

You can run `com.mattstine.dddworkshop.pizzashop.suites.Lab3Suite` to check your progress in this lab.

== Instructions

. `KitchenOrder` has an associated `KitchenOrderRef` type. Complete its implementation. Look for hints in the `Ref` types found in the Ordering and Payments contexts.

. `Pizza` has an associated `PizzaRef` type. Complete its implementation. Look for hints in the `Ref` types found in the Ordering and Payments contexts.

. `KitchenOrder` has an internal static class called `OrderState` that captures the initial state snapshot for the `KitchenOrder`. It is returned by the `state()` method. Complete these implementations. Look for hints in the `Aggregate` types found in the Ordering and Payments contexts.

. `Pizza` has an internal static class called `PizzaState` that captures the initial state snapshot for the `Pizza`. It is returned by the `state()` method. Complete these implementations. Look for hints in the `Aggregate` types found in the Ordering and Payments contexts. 

. Change the `script` property in `.travis.yml` to read: `mvn test -B -P Lab3`

. When you've completed the lab, be sure to submit your work to GitHub using a `[LAB 3]` prefix on your commit message.
